version: '3'

services:
  goapp:
    build: ./goapp
    ports:
      - "38081:38081"
    volumes:
      - log_data:/goapp/log

  fluent-bit:
    image: fluent/fluent-bit:2.2
    container_name: fluent-bit
    volumes:
      - ./fluent-bit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit/parsers.conf:/fluent-bit/etc/parsers.conf
      - log_data:/log
    depends_on:
      - goapp
    ports:
      - "2020:2020"
      - "2021:2021"
    command: ["fluent-bit", "-c", "/fluent-bit/etc/fluent-bit.conf"]

  elasticsearch:
    image: elasticsearch:7.17.13
    container_name: elasticsearch-1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:7.17.13
    container_name: kibana-1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  es_data:
    driver: local
  log_data:
    driver: local